import AppKit
import os

/// Watches the general pasteboard for changes, classifies each capture, and
/// hands it to StorageService.
///
/// `NSPasteboard` has no change-notification API, so polling `changeCount`
/// is the only option. All pasteboard access happens on one
/// serial background queue: the main thread is never involved, and
/// serialising every access sidesteps NSPasteboard's undocumented threading
/// behaviour.
///
/// `@unchecked Sendable` because all mutable state is confined to `queue`;
/// the compiler cannot see GCD confinement, so we assert it manually.
nonisolated final class ClipboardMonitor: @unchecked Sendable {

    private static let pollInterval: DispatchTimeInterval = .milliseconds(200)
    private static let debounceInterval: DispatchTimeInterval = .milliseconds(120)

    /// Standard markers (see nspasteboard.org) applied by password managers
    /// and autofill. Anything carrying one of these must never reach any
    /// other code path.
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let logger = Logger(subsystem: "com.clip.app", category: "ClipboardMonitor")
    private let queue = DispatchQueue(label: "com.clip.app.clipboard-monitor", qos: .utility)
    /// nil when the store failed to open at launch — captures are then
    /// logged as dropped rather than dying silently.
    private let storage: StorageService?
    /// Fired after each successful store — AppDelegate points this at the
    /// RetentionEngine so pruning follows every capture.
    var onItemStored: (@Sendable () -> Void)?

    // Everything below is touched only on `queue`.
    private var timer: DispatchSourceTimer?
    private var lastChangeCount = 0
    private var isReadPending = false

    init(storage: StorageService?) {
        self.storage = storage
    }

    func start() {
        queue.async { [self] in
            guard timer == nil else { return }
            // Baseline against the current count so whatever was already on
            // the clipboard before launch is not captured.
            lastChangeCount = NSPasteboard.general.changeCount

            let source = DispatchSource.makeTimerSource(queue: queue)
            source.schedule(deadline: .now() + Self.pollInterval, repeating: Self.pollInterval)
            source.setEventHandler { [weak self] in
                self?.poll()
            }
            source.resume()
            timer = source
            logger.log("Clipboard monitoring started")
        }
    }

    func stop() {
        queue.async { [self] in
            timer?.cancel()
            timer = nil
        }
    }

    // MARK: - Polling

    /// Must stay this cheap — one integer read and a compare.
    private func poll() {
        guard NSPasteboard.general.changeCount != lastChangeCount, !isReadPending else { return }
        // Debounce: rapid successive copies, and apps that write several
        // representations in quick succession, coalesce into a single read of
        // whatever the pasteboard holds once the delay expires.
        isReadPending = true
        queue.asyncAfter(deadline: .now() + Self.debounceInterval) { [weak self] in
            self?.readPasteboard()
        }
    }

    private func readPasteboard() {
        isReadPending = false
        let pasteboard = NSPasteboard.general
        // Sync to the count we are about to read so this change — and any that
        // landed during the debounce window — is not re-detected next poll.
        lastChangeCount = pasteboard.changeCount

        // Master toggle: checked per detected change, not per poll,
        // so the polling path stays a bare integer compare.
        guard AppSettings.historyEnabled else {
            logger.debug("Capture skipped: history is paused")
            return
        }

        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty else { return }

        // Privacy gate — must run before any other handling.
        // Deliberately silent: a password-manager copy must leave no trace,
        // not even a log line.
        guard Self.concealedTypes.isDisjoint(with: types) else { return }

        let string = pasteboard.string(forType: .string)
        let kind = ItemClassifier.classify(types: types, string: string)
        let sourceApp = NSWorkspace.shared.frontmostApplication

        guard let capture = makeCapture(kind: kind, pasteboard: pasteboard, string: string, sourceApp: sourceApp) else {
            logger.debug("Ignored capture with no storable payload")
            return
        }

        // Privacy & filter rules. Content never reaches the log —
        // only the rule that fired.
        if let reason = CaptureFilter.skipReason(for: capture, rules: .current()) {
            logger.log("Skipped \(kind.rawValue, privacy: .public) capture: \(reason.rawValue, privacy: .public)")
            return
        }

        guard let storage else {
            logger.error("Dropped \(kind.rawValue, privacy: .public) capture — storage unavailable")
            return
        }

        // Hashing and the database write happen inside the storage actor,
        // off this queue; the monitor is free to keep polling meanwhile.
        Task { [logger, onItemStored] in
            do {
                // A dedupe only refreshes lastUsedAt — no new row, so no
                // retention trigger; the periodic sweep covers age pruning.
                if try await storage.save(capture) == .inserted {
                    onItemStored?()
                }
            } catch {
                // Never silent: a lost item is a bug the user will notice
                // and struggle to reproduce (CLAUDE.md).
                logger.error("Failed to store \(kind.rawValue, privacy: .public) capture: \(String(describing: error), privacy: .public)")
            }
        }
    }

    // MARK: - Capture assembly

    private func makeCapture(
        kind: ItemKind,
        pasteboard: NSPasteboard,
        string: String?,
        sourceApp: NSRunningApplication?
    ) -> CapturedItem? {
        let sourceID = sourceApp?.bundleIdentifier
        let sourceName = sourceApp?.localizedName

        switch kind {
        case .image:
            // Prefer PNG; fall back to TIFF. Raw data only — no NSImage
            // decode at capture time.
            let payload: (data: Data, ext: String)?
            if let png = pasteboard.data(forType: .png) {
                payload = (png, "png")
            } else if let tiff = pasteboard.data(forType: .tiff) {
                payload = (tiff, "tiff")
            } else {
                payload = nil
            }
            guard let payload else { return nil }
            let size = ByteCountFormatter.string(fromByteCount: Int64(payload.data.count), countStyle: .file)
            return CapturedItem(
                kind: kind,
                textContent: nil,
                blobData: payload.data,
                blobFileExtension: payload.ext,
                preview: "Image (\(size))",
                byteSize: payload.data.count,
                sourceAppID: sourceID,
                sourceAppName: sourceName
            )

        case .file:
            let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL] ?? []
            guard !urls.isEmpty else { return nil }
            // Files are stored as *references* (paths), not payload copies,
            // so a path only resolves for as long as the file stays put.
            let paths = urls.map(\.path).joined(separator: "\n")
            let names = urls.map(\.lastPathComponent).joined(separator: ", ")
            return CapturedItem(
                kind: kind,
                textContent: paths,
                blobData: nil,
                blobFileExtension: nil,
                preview: Self.preview(of: names),
                byteSize: paths.utf8.count,
                sourceAppID: sourceID,
                sourceAppName: sourceName
            )

        case .text, .link, .colour, .code:
            guard let string,
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            else { return nil }
            return CapturedItem(
                kind: kind,
                textContent: string,
                blobData: nil,
                blobFileExtension: nil,
                preview: Self.preview(of: string),
                byteSize: string.utf8.count,
                sourceAppID: sourceID,
                sourceAppName: sourceName
            )
        }
    }

    /// Single-line display string, max 200 characters.
    /// Internal (not private) so the flattening rules are unit-testable.
    static func preview(of string: String) -> String {
        // A capture can legally be megabytes of text; never flatten the whole
        // thing to produce 200 characters. Double the limit leaves headroom
        // for whitespace that flattening trims away.
        let (head, capped) = string.previewCapped(to: previewLimit * 2)
        // Character-wise so "\r\n" (one grapheme) becomes one space, and
        // Unicode line/paragraph separators flatten too.
        let flattened = String(head.map { $0.isNewline ? " " : $0 })
            .trimmingCharacters(in: .whitespaces)
        guard capped || flattened.count > previewLimit else { return flattened }
        return String(flattened.prefix(previewLimit - 1)) + "…"
    }

    private static let previewLimit = 200
}
